name: Update Visualization

on:
  schedule:
    - cron: '30 21 * * 1-5'  # Run at 5 PM UTC (market close) on weekdays
  workflow_dispatch:        # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/sp500_visualization.R') }}-1
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R packages
      run: |
        Rscript -e 'if(!dir.exists(Sys.getenv("R_LIBS_USER"))) dir.create(Sys.getenv("R_LIBS_USER"), recursive=TRUE)'
        Rscript -e 'install.packages(c("quantmod", "dplyr", "lubridate", "plotly", "htmlwidgets"), repos = "https://cloud.r-project.org/", lib=Sys.getenv("R_LIBS_USER"))'
        
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
        
    - name: Run visualization script
      run: Rscript sp500_visualization.R
        
    - name: Render Quarto document
      run: |
        quarto render index.qmd
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: true
