name: Update Visualization

on:
  schedule:
    - cron: '0 17 * * 1-5'  # Run at 5 PM UTC (market close) on weekdays
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("quantmod", "dplyr", "lubridate", "plotly", "htmlwidgets"), repos = "https://cloud.r-project.org/")'
        
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.3.450
        
    - name: Run visualization script
      run: Rscript sp500_visualization.R
        
    - name: Render Quarto document
      run: quarto render index.qmd
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: true
